# Generated by Django 4.2.10 on 2024-02-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdata',
            table='userdatas',
        ),
    ]
