# Generated by Django 4.2.10 on 2024-02-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_books_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CART',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverimg_cart', models.ImageField(upload_to='')),
                ('bookname_cart', models.CharField(max_length=255)),
                ('authorname_cart', models.CharField(max_length=255)),
                ('price_cart', models.IntegerField()),
            ],
            options={
                'db_table': 'cartdata',
            },
        ),
    ]
