# Generated by Django 4.2.10 on 2024-02-23 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price_cart',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='authorname_cart',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='bookname_cart',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='coverimg_cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.books'),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.userdata'),
        ),
    ]
