# Generated by Django 4.2.10 on 2024-02-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_books_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='publication_date',
            field=models.DateField(null=True),
        ),
    ]
