# Generated by Django 5.0.2 on 2024-02-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('book_description', models.TextField()),
                ('book_image', models.ImageField(upload_to='media')),
            ],
            options={
                'db_table': 'bookstore',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=10)),
                ('user_number', models.CharField(max_length=10)),
                ('user_image', models.ImageField(upload_to='media')),
            ],
            options={
                'db_table': 'userdetails',
            },
        ),
    ]
